version: '2'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose --future
    environment:
      JEKYLL_ENV: development
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
