name: Build

on:
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Bundle install
      run: |
        gem install bundler:2.2.12
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build with Jekyll
      run: |
        bundle exec jekyll build
