name: Publish content before merging

on:
  push:
    # to be changed to 'main'
    branches: ['publish-article-pipeline']

jobs:
  check-unpublished:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Should publish
        id: should-publish
        run: echo "::set-output name=should-publish::$([[ -d "content/posts/unpublished" ]] && echo true || echo false)"
      
  publish:
    runs-on: ubuntu-latest
    needs: check-unpublished
    if: ${{needs.check-unpublished.outputs.should-publish}}
    steps:
      - run: echo "run"