name: Publish content before merging

on:
  merge_group:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build:utils
      - name: Set date to new article
        id: publish
        run: npm run posts:publish
      - name: Commit files
        if: steps.publish.outputs.publish == 'published'
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |
         git config --local user.email "oss@backbase.com"
         git config --local user.name "backbaseoss"
         git commit -m "Publish article" -a
         git push
